#
# CircleCI Integration Tests.
# Run locally with circleci local:
#
#   `circleci build`
#
# For using anchors in circle.yml see https://circleci.com/docs/2.0/writing-yaml/#anchors-and-aliases
#
# NOTE: As of today 2018-11 circleci local doesn't
#       support caching.
#
anchors:
- key_cache: &key_cache v1-cache-{{ checksum "python-flask/requirements.txt" }}
- apt_cache: &apt_cache v1-apt-cache-{{ checksum ".circleci/config.yml" }}

version: 2
jobs:
  build: &base
    docker:
      - image: circleci/golang:1.12
    working_directory: /tmp/code
    steps:
    - checkout

    - run: sudo apt -y update && sudo apt -y install tox make

    - run: make yaml

    - run: go get -u github.com/deepmap/oapi-codegen/cmd/oapi-codegen

    - run: |
        make test-chi


workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build

